"""YouTube upload service for automated posting from the Celery worker.

This module provides a synchronous upload function that can be called
directly from the pipeline task after a video is successfully generated
and uploaded to blob storage.
"""

import os
import tempfile
import time
from datetime import datetime, timedelta

import requests
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from app.config import settings
from app.database import cosmos_db

GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"


def _get_youtube_credentials(user_id: str) -> Credentials | None:
    """Load YouTube OAuth2 credentials for a user from Cosmos DB.

    Returns None if the user has not connected a YouTube account.
    """
    accounts = cosmos_db.query_items(
        "youtube_accounts",
        "SELECT * FROM c WHERE c.user_id = @uid",
        [{"name": "@uid", "value": user_id}],
    )
    if not accounts:
        return None

    account = accounts[0]
    creds = Credentials(
        token=account.get("access_token"),
        refresh_token=account.get("refresh_token"),
        token_uri=GOOGLE_TOKEN_URL,
        client_id=settings.youtube_client_id,
        client_secret=settings.youtube_client_secret,
    )

    return creds


def _persist_refreshed_token(user_id: str, creds: Credentials):
    """Write back a refreshed access token to Cosmos DB."""
    accounts = cosmos_db.query_items(
        "youtube_accounts",
        "SELECT * FROM c WHERE c.user_id = @uid",
        [{"name": "@uid", "value": user_id}],
    )
    if not accounts:
        return
    account = accounts[0]
    account["access_token"] = creds.token
    if creds.expiry:
        account["expires_at"] = creds.expiry.isoformat()
    cosmos_db.upsert_item("youtube_accounts", account)


# Category -> hashtags for YouTube SEO / virality
_CATEGORY_HASHTAGS = {
    "horror": ["#horror", "#horrorstory", "#scary", "#bhoot", "#darawnikahani"],
    "funny": ["#funny", "#comedy", "#funnyvideo", "#mazak", "#hasimajak"],
    "crime": ["#crime", "#crimestory", "#truecrime", "#apradh", "#crimekahani"],
    "thriller": ["#thriller", "#suspense", "#thrillerstory", "#rahasya"],
    "history": ["#history", "#historyfacts", "#itihas", "#historystory"],
    "mystery": ["#mystery", "#mysterystory", "#rahasya", "#unsolved"],
    "adult": ["#story", "#drama", "#kahani", "#hindistory"],
    "custom": ["#story", "#aistory", "#kahani"],
}

# Default hashtags always appended
_DEFAULT_HASHTAGS = ["#shorts", "#viral", "#trending", "#story", "#ai", "#minitale"]


def _build_viral_title(title: str, category: str, language: str) -> str:
    """Build a YouTube-optimized dual-language title with hashtags.

    Format: English Title | Hindi Title #category #shorts #viral ...
    YouTube Shorts titles are capped at 100 chars.
    """
    # Category hashtags
    cat_tags = _CATEGORY_HASHTAGS.get(category.lower(), _CATEGORY_HASHTAGS["custom"])

    # Combine: 2 category tags + default tags
    hashtag_str = " ".join(cat_tags[:2] + _DEFAULT_HASHTAGS[:4])

    # Build dual-language title if Hindi
    if language.lower() == "hindi":
        yt_title = f"{title} | {title} {hashtag_str}"
    else:
        yt_title = f"{title} {hashtag_str}"

    # YouTube title max 100 chars
    if len(yt_title) > 100:
        yt_title = yt_title[:97] + "..."

    return yt_title


def _build_viral_description(title: str, category: str, language: str) -> str:
    """Build a YouTube-optimized description with hashtags for discoverability."""
    cat_tags = _CATEGORY_HASHTAGS.get(category.lower(), _CATEGORY_HASHTAGS["custom"])
    all_tags = cat_tags + _DEFAULT_HASHTAGS

    desc_lines = [
        f"{title}",
        "",
        f"Generated by MiniTaleStudio - AI Story Video Platform",
        f"Category: {category.capitalize()}",
        f"Language: {language.capitalize()}",
        "",
        " ".join(all_tags),
        "",
        "Subscribe for more AI-generated stories!",
    ]
    return "\n".join(desc_lines)


def _build_viral_tags(title: str, category: str, language: str) -> list[str]:
    """Build a tag list for YouTube SEO."""
    base_tags = ["MiniTaleStudio", "AI", "shorts", "short story", "viral"]
    cat = category.lower()
    base_tags.append(cat)
    if language.lower() == "hindi":
        base_tags += ["hindi", "hindi story", "hindi kahani", "kahani"]
    else:
        base_tags += ["english", "english story"]
    # Add title words as tags (skip short words)
    for word in title.split():
        clean = word.strip(".,!?#|").lower()
        if len(clean) > 3 and clean not in base_tags:
            base_tags.append(clean)
    return base_tags[:30]  # YouTube allows max ~30 effective tags


def upload_to_youtube(
    user_id: str,
    video_source: str,
    title: str,
    category: str = "",
    language: str = "",
) -> dict | None:
    """Upload a video to YouTube.

    Args:
        user_id: The user whose YouTube account to use.
        video_source: A blob URL (https://...) or local file path.
        title: Video title.
        category: Story category for the description.
        language: Story language for the description.

    Returns:
        A dict with ``youtube_video_id`` and ``youtube_url`` on success,
        or ``None`` if the user has no connected YouTube account.

    Raises:
        RuntimeError: If the upload fails for a technical reason.
    """
    if not settings.youtube_client_id or not settings.youtube_client_secret:
        print("[YouTube] YouTube API credentials not configured, skipping auto-upload")
        return None

    creds = _get_youtube_credentials(user_id)
    if creds is None:
        print(f"[YouTube] No YouTube account connected for user {user_id}, skipping auto-upload")
        return None

    # Build the YouTube Data API service
    youtube = build("youtube", "v3", credentials=creds)

    # Persist refreshed token if it changed
    if creds.token:
        _persist_refreshed_token(user_id, creds)

    # Prepare the video file
    tmp_path = None
    try:
        if video_source.startswith("http"):
            # Download from blob to a temp file
            tmp_dir = tempfile.mkdtemp()
            tmp_path = os.path.join(tmp_dir, "upload.mp4")
            print(f"[YouTube] Downloading video for upload: {video_source[:80]}...")
            resp = requests.get(video_source, stream=True, timeout=300)
            resp.raise_for_status()
            with open(tmp_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    f.write(chunk)
            upload_path = tmp_path
        elif os.path.exists(video_source):
            upload_path = video_source
        else:
            print(f"[YouTube] Video source not accessible: {video_source}")
            return None

        yt_title = _build_viral_title(title or "MiniTale Story", category, language)
        yt_description = _build_viral_description(title or "MiniTale Story", category, language)
        yt_tags = _build_viral_tags(title or "MiniTale Story", category, language)

        body = {
            "snippet": {
                "title": yt_title,
                "description": yt_description,
                "tags": yt_tags,
                "categoryId": "22",  # People & Blogs
            },
            "status": {
                "privacyStatus": "public",
                "selfDeclaredMadeForKids": False,
            },
        }

        media = MediaFileUpload(upload_path, mimetype="video/mp4", resumable=True)
        insert_request = youtube.videos().insert(
            part="snippet,status", body=body, media_body=media
        )

        print(f"[YouTube] Starting upload: {title}")
        response = None
        while response is None:
            upload_status, response = insert_request.next_chunk()
            if upload_status:
                print(f"[YouTube] Upload progress: {int(upload_status.progress() * 100)}%")

        youtube_video_id = response["id"]
        youtube_url = f"https://youtube.com/watch?v={youtube_video_id}"
        print(f"[YouTube] Upload SUCCESS: {youtube_url}")

        return {
            "youtube_video_id": youtube_video_id,
            "youtube_url": youtube_url,
        }

    except Exception as e:
        print(f"[YouTube] Auto-upload FAILED: {type(e).__name__}: {e}")
        raise RuntimeError(f"YouTube upload failed: {e}") from e

    finally:
        # Clean up temp file
        if tmp_path and os.path.exists(tmp_path):
            for attempt in range(3):
                try:
                    os.remove(tmp_path)
                    break
                except PermissionError:
                    time.sleep(1)
            try:
                parent = os.path.dirname(tmp_path)
                if os.path.exists(parent):
                    os.rmdir(parent)
            except OSError:
                pass
